### ISSUE TITLE
Anomaly in template literals results

### ISSUE THREAD

**Issue by nikcorg** [CoffeeAndCode/whatdoeslambdasupport.com#7]
The test results for template literals looks funny:

![screen shot 2017-01-12 at 18 16 34](https://cloud.githubusercontent.com/assets/816988/21902301/4ed04816-d8f3-11e6-97b1-938c093418fa.png)

The [basic functionality test](https://github.com/kangax/compat-table/blob/gh-pages/data-es6.js#L4339-L4343) is possibly being run with the leading indentation on line three of the test code template not properly trimmed out, causing the results to not match.

Might be worth checking out that one, and maybe others, too.

Edit. Could maybe be fixed just by using [Kangax's deindenter](https://github.com/kangax/compat-table/blob/gh-pages/build.js#L708-L715). I get different results from it, compared to [the one in this project](https://github.com/CoffeeAndCode/whatdoeslambdasupport.com/blob/master/functions/tester.js#L24-L40).

**Comment by jonknapp** [comment]
👍 thanks for the heads up! (and for attending my talk, which is where I'm guessing you found the project)

**Comment by nikcorg** [comment]
Nope, found it from a friend's tweet :-)

**Comment by jonknapp** [comment]
Even better! Thanks for stopping by.

**Comment by jonknapp** [comment]
After jumping back into this project, things are WAY more difficult than I originally remember them. I'll poke around and try to clean up getting this to work locally as well as split the html creation from the deployment tasks to make it easier to track things like this down when they need fixed. Thanks again for pointing out this flaw.

**Comment by jlsjonas** [comment]
why would you want to split that? also is there any news so far? (as it's been almost a year 😅 )

**Comment by jonknapp** [comment]
The current code compiles the final html and then tries to add it to S3. Ideally those would be separate tasks so someone wouldn't have to jump in the code and add a bunch of log statements for example.

Been a bit busy this year (first child and growing the company a bit) so this has taken a back seat. Pull requests always welcomed!

**Comment by jonknapp** [comment]
At this point, I'm not sure the site is providing much value since many of the "js-next" features are now commonly found in the versions that AWS Lambda supports. I recently let the website expire so I'll be closing all open issues for now.

I'll leave the project on Github in case it interests anyone.
